// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTK9JQqj5aRC9M8oCMyG8MY5YySkudpnI',
    appId: '1:108602706908:web:2147d5c1ad8a324ec85d19',
    messagingSenderId: '108602706908',
    projectId: 'corgis-ai-push-notification',
    authDomain: 'corgis-ai-push-notification.firebaseapp.com',
    storageBucket: 'corgis-ai-push-notification.appspot.com',
    measurementId: 'G-89Y133WDSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARqzh4AlAXPr_y2bQP3mbSd0fJpGydoM0',
    appId: '1:108602706908:android:af041d9b9185d31ec85d19',
    messagingSenderId: '108602706908',
    projectId: 'corgis-ai-push-notification',
    storageBucket: 'corgis-ai-push-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAicdl8wfcgkkLhwrjsomJ_qPW0oUARJ_I',
    appId: '1:108602706908:ios:003f74ca08a59f4cc85d19',
    messagingSenderId: '108602706908',
    projectId: 'corgis-ai-push-notification',
    storageBucket: 'corgis-ai-push-notification.appspot.com',
    iosBundleId: 'com.example.corgisAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAicdl8wfcgkkLhwrjsomJ_qPW0oUARJ_I',
    appId: '1:108602706908:ios:08ba5b2ad456470bc85d19',
    messagingSenderId: '108602706908',
    projectId: 'corgis-ai-push-notification',
    storageBucket: 'corgis-ai-push-notification.appspot.com',
    iosBundleId: 'com.example.corgisAiApp.RunnerTests',
  );
}
